### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pablo33** [pablo33/synology-UPS-snmp-monitor#1]
Need a loggin module implementation.

```
Traceback (most recent call last):
  File "/opt/synology-UPS-monitor/synoUPSmonitor.py", line 185, in <module>
    Con.updatevalues()
  File "/opt/synology-UPS-monitor/synoUPSmonitor.py", line 46, in decorator
    return fx(*args, **kw_args)
  File "/opt/synology-UPS-monitor/synoUPSmonitor.py", line 95, in updatevalues
    id, value = Con.getdata(datadict['BatteryChargeValue'])
  File "/opt/synology-UPS-monitor/synoUPSmonitor.py", line 46, in decorator
    return fx(*args, **kw_args)
  File "/opt/synology-UPS-monitor/synoUPSmonitor.py", line 80, in getdata
    value = float.fromhex(value)
ValueError: invalid hexadecimal floating-point string
```

**Comment by pablo33** [comment]
Trying to catch a value.
